# Change these first
owner: devoplus # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Devoplus API
    url: https://api.devoplus.com.tr
    icon: https://icons.duckduckgo.com/ip3/portal.devoplus.com.tr.ico
    expectedStatusCodes:
      - 200
      - 401
  - name: Devoplus Portal
    url: https://portal.devoplus.com.tr
    expectedStatusCodes:
      - 200  
  - name: Devoplus SSO
    url: https://sso.devoplus.com.tr
    expectedStatusCodes:
      - 200
  - name: URL Shortener Service
    url: https://dv.ls
    expectedStatusCodes:
      - 200
  - name: Mail Queue Handler Service
    check: "tcp-ping"
    url: smtp-relay.devoplus.email
    port: 587
    icon: https://icons.duckduckgo.com/ip3/portal.devoplus.com.tr.ico
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.devo.plus
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/devoplus/upptime/master/assets/dp-icon.png
  favicon: https://www.devoplus.com.tr/favicon.png
  name: Devoplus
  introTitle: "**Devoplus** Servis Durumu"
  introMessage: Bu panel, Devoplus altyapısına ait servislerin mevcut çalışma durumunu, geçmiş olay geçmişini ve planlı bakım süreçlerini şeffaf bir şekilde sunmak amacıyla hazırlanmıştır. Sistem izleme mekanizmalarımız; API uç noktaları, veri işleme hatları, kullanıcı arayüzleri ve entegrasyon servisleri dahil olmak üzere tüm temel bileşenlerdeki performans ve sürekliliği sürekli olarak denetlemektedir. Herhangi bir anomali veya kesinti tespit edildiğinde ilgili bilgilendirme otomatik olarak burada yayınlanır. Hizmet sürekliliğini önceliğimiz olarak görüyor, kullanıcılarımıza kesintisiz bir deneyim sağlamak için proaktif olarak çalışıyoruz.
  navbar:
    - title: Servis Durumu
      href: /

i18n:
  activeIncidents: Aktif Vakalar
  allSystemsOperational: Tüm sistemler çalışır durumda
  incidentReport: "Vaka #$NUMBER Raporu →"
  incidentTitle: Vaka $NUMBER Detayları
  incidentDetails: Vaka Detayları
  liveStatus: Canlı Durum
  loading: Yükleniyor
  duration24H: "24 Saat"
  duration7D: "7 Gün"
  duration30D: "30 Gün"
  duration1Y: "1 Yıl"
  durationAll: "Tümü"
  overallUptime: "Uptime: $UPTIME"
  overallUptimeTitle: Uptime
  averageResponseTime: "Ortalama Yanıt Süresi: $TIMEms"
  averageResponseTimeTitle: Ortalama Yanıt Süresi
  locale: tr-TR

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
